name = "file-share"
main = "src/worker.js"
compatibility_date = "2025-01-01"
keep_vars = true

[assets]
directory = "./public"
run_worker_first = ["/api/*"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "file-share"

[vars]
MAX_BYTES = "10000000000"   # 10 GB total cap
